"""Rule-based scorer for institutional_flow source class.

Why not FinBERT:
    Congressional trade posts look like:
    "Representative X (R) bought $50,000 of NVDA on 2026-04-15. Congressional STOCK Act disclosure."
    FinBERT scores financial news sentiment. It doesn't know that "bought" = bullish
    and "sold" = bearish in this context — it just sees neutral financial text.
    A rule-based scorer is more accurate, faster, and free.

Scoring logic:
    Purchase → polarity = +min(1.0, log10(amount) / 6)
               (log10 scale: $10K=+0.67, $100K=+0.83, $1M=+1.0)
    Sale      → polarity = -min(1.0, log10(amount) / 6)
    Unknown   → polarity = 0.0

    confidence = min(1.0, log10(amount) / 7)
               (larger trades = higher confidence, capped at 1.0)

    Rationale for log scale: a $1M trade is more signal than a $10K trade,
    but not 100x more signal. Log compression captures this diminishing return.

Integration:
    Called by the orchestrator as a post-processing step after ingest-all.
    Reads unscored institutional_flow rows from raw_posts.
    Writes to sentiment_scores exactly like FinBERT does.
    Uses the same scoring_watermark table for dedup.

Congressional trades are tier B — moderate weight in divergence math.
"""
from __future__ import annotations

import logging
import math
from datetime import datetime, timezone

from alphahound.engine.storage import get_conn

log = logging.getLogger(__name__)

SOURCE_CLASS = "institutional_flow"
PULL_BATCH_SIZE = 500   # institutional_flow has fewer posts, can batch larger

# Minimum amount ($) to produce a non-zero score.
# Below this threshold the trade is too small to be meaningful.
MIN_AMOUNT = 1_000.0

# Log scale divisor. log10($1M) = 6, so dividing by 6 gives max polarity of 1.0
# for trades >= $1M. Adjust if you want different scaling.
LOG_SCALE = 6.0


def score_institutional_flow(dry_run: bool = False) -> int:
    """Score all unscored institutional_flow posts. Returns rows written."""
    watermark = _get_watermark()
    log.info(
        "Institutional flow scorer: since %s",
        watermark.isoformat() if watermark else "beginning of time",
    )

    total_written = 0

    while True:
        posts = _pull_unscored(watermark, limit=PULL_BATCH_SIZE)
        if not posts:
            break

        rows = []
        for post in posts:
            polarity, confidence = _score_post(post)
            tier = post.get("tier", "B")
            rows.append((
                post["time"],
                post["entity_id"],
                SOURCE_CLASS,
                polarity,
                confidence,
                tier,
                1,
            ))

        if not dry_run:
            written = _write_scores(rows)
            total_written += written
            latest = max(p["time"] for p in posts)
            _set_watermark(latest)
            watermark = latest
        else:
            log.info("(dry-run) Would write %d institutional_flow scores", len(rows))
            break

        if len(posts) < PULL_BATCH_SIZE:
            break

    log.info("Institutional flow scorer: wrote %d scores", total_written)
    return total_written


def _score_post(post: dict) -> tuple[float, float]:
    """Derive (polarity, confidence) from a congressional trade post.

    Parses the synthetic text generated by the Quiver adapter:
        "Representative X (Party) bought/sold $AMOUNT of TICKER on DATE."

    Falls back to raw JSON fields if text parsing fails.
    """
    text  = (post.get("text") or "").lower()
    raw   = post.get("raw") or {}

    # 1. Determine direction from text.
    if "bought" in text or "purchase" in text:
        direction = 1
    elif "sold" in text or "sale" in text:
        direction = -1
    else:
        # Try raw transaction field from Quiver.
        txn = (raw.get("Transaction") or raw.get("transaction") or "").lower()
        if "purchase" in txn or "buy" in txn:
            direction = 1
        elif "sale" in txn or "sell" in txn:
            direction = -1
        else:
            return (0.0, 0.0)

    # 2. Extract dollar amount.
    amount = _extract_amount(text, raw)
    if amount < MIN_AMOUNT:
        return (0.0, 0.0)

    # 3. Log-scale polarity and confidence.
    log_amount  = math.log10(max(amount, 1.0))
    polarity    = round(direction * min(1.0, log_amount / LOG_SCALE), 4)
    confidence  = round(min(1.0, log_amount / (LOG_SCALE + 1)), 4)

    return (polarity, confidence)


def _extract_amount(text: str, raw: dict) -> float:
    """Extract trade dollar amount from text or raw dict."""
    # Try raw dict first — more reliable.
    for key in ("Amount", "amount", "transaction_amount"):
        val = raw.get(key)
        if val:
            amount = _parse_amount_string(str(val))
            if amount > 0:
                return amount

    # Parse from text: look for "$X,XXX" or "$X.XM" patterns.
    import re
    # Match patterns like "$50,000" or "$1,000,000"
    matches = re.findall(r'\$([0-9,]+)', text)
    for m in matches:
        try:
            val = float(m.replace(",", ""))
            if val >= MIN_AMOUNT:
                return val
        except ValueError:
            continue

    return 0.0


def _parse_amount_string(s: str) -> float:
    """Parse Quiver's amount range strings to midpoint float.

    Quiver uses ranges like "$15,001 - $50,000". We use the midpoint.
    """
    AMOUNT_MAP = {
        "$1,001 - $15,000":          8_000,
        "$15,001 - $50,000":        32_500,
        "$50,001 - $100,000":       75_000,
        "$100,001 - $250,000":     175_000,
        "$250,001 - $500,000":     375_000,
        "$500,001 - $1,000,000":   750_000,
        "$1,000,001 - $5,000,000": 3_000_000,
        "$5,000,001 - $25,000,000": 15_000_000,
    }
    midpoint = AMOUNT_MAP.get(s.strip())
    if midpoint:
        return float(midpoint)
    # Try direct parse.
    try:
        return float(s.replace(",", "").replace("$", "").strip())
    except ValueError:
        return 0.0


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def _pull_unscored(since: datetime | None, limit: int) -> list[dict]:
    """Pull unscored institutional_flow posts."""
    with get_conn() as conn:
        with conn.cursor() as cur:
            if since is None:
                cur.execute(
                    """
                    SELECT rp.post_id, rp.time, rp.entity_id, rp.adapter_id,
                           rp.source_class, rp.tier, rp.text, rp.raw
                    FROM raw_posts rp
                    WHERE rp.source_class = %s
                      AND NOT EXISTS (
                          SELECT 1 FROM sentiment_scores ss
                          WHERE ss.entity_id = rp.entity_id
                            AND ss.source_class = rp.source_class
                            AND ss.time = rp.time
                      )
                    ORDER BY rp.time ASC
                    LIMIT %s;
                    """,
                    (SOURCE_CLASS, limit),
                )
            else:
                cur.execute(
                    """
                    SELECT rp.post_id, rp.time, rp.entity_id, rp.adapter_id,
                           rp.source_class, rp.tier, rp.text, rp.raw
                    FROM raw_posts rp
                    WHERE rp.source_class = %s
                      AND rp.time > %s
                      AND NOT EXISTS (
                          SELECT 1 FROM sentiment_scores ss
                          WHERE ss.entity_id = rp.entity_id
                            AND ss.source_class = rp.source_class
                            AND ss.time = rp.time
                      )
                    ORDER BY rp.time ASC
                    LIMIT %s;
                    """,
                    (SOURCE_CLASS, since, limit),
                )
            cols = [d.name for d in cur.description]
            return [dict(zip(cols, row)) for row in cur.fetchall()]


def _write_scores(rows: list[tuple]) -> int:
    """Write scored rows to sentiment_scores. Returns rows written."""
    if not rows:
        return 0
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.executemany(
                """
                INSERT INTO sentiment_scores
                    (time, entity_id, source_class, polarity, confidence, tier, post_count)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (entity_id, source_class, time) DO NOTHING;
                """,
                rows,
            )
            written = cur.rowcount
        conn.commit()
    return written


def _get_watermark() -> datetime | None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT last_scored_at FROM scoring_watermark WHERE source_class = %s;",
                (SOURCE_CLASS,),
            )
            row = cur.fetchone()
    return row[0] if row else None


def _set_watermark(ts: datetime) -> None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO scoring_watermark (source_class, last_scored_at)
                VALUES (%s, %s)
                ON CONFLICT (source_class) DO UPDATE
                    SET last_scored_at = EXCLUDED.last_scored_at,
                        updated_at = now();
                """,
                (SOURCE_CLASS, ts),
            )
        conn.commit()
